### ISSUE TITLE
"Pause" does nothing

### ISSUE THREAD

**Issue by pjscopeland** [alexch/rerun#100]
When rerun is doing its thing, pressing `p` should pause the file system watcher. But when I press `p`, no matter whether I'm in the middle of a run, or between runs, nothing happens. I get no feedback, and if I save a file, rerun restarts.

**Comment by nilbus** [comment]
For me on 0.11.0, pausing with `p` works, but it won't resume.

**Comment by alexch** [comment]
What OS are you on? Please try pressing `return` after `p` (since on some systems the input gets fed in one line at a time, not one character at a time).

**Comment by pjscopeland** [comment]
I'm in the same position as @nilbus now. `Return` doesn't help.

**Comment by nilbus** [comment]
I'm running in Linux. All other characters are picked up immediately, not requiring a newline. 

After pressing `p` initially, I see

    [rerun] Pausing.  Press 'p' again to resume.

Afterward, pressing `p` (unlike other unmapped characters) gives no output, other than echoing the `p` that was pressed.

I tested on 0.11. and 0.12.0.

**Comment by pjscopeland** [comment]
I'm on OSX and I get the same output, but saving a file doesn't restart the process. I haven't tried pressing `r` yet.

**Comment by alexch** [comment]
I switched my main dev machine to Windows last year, so it'll be a little while before I can repro this. Thanks for the reports.

**Comment by bsia** [comment]
I can repro this on my mac and I think I have a fix for it.  Currently testing.

**Comment by alexch** [comment]
Fixed by Barry! Thanks.  2474eb21168bf263ab60450d83566f1e24568b87
