### ISSUE TITLE
ffi incompatibility with my version of ruby on installation using gem

### ISSUE THREAD

**Issue by RomanADavis** [alexch/rerun#112]
```
PS C:\Users\TOSHIBA\Desktop\learn-ruby\learn_ruby_the_hard_way\gothomweb> gem install rerun
ERROR:  Error installing rerun:
        ffi requires Ruby version < 2.5, >= 2.0.
PS C:\Users\TOSHIBA\Desktop\learn-ruby\learn_ruby_the_hard_way\gothomweb>

```

**Comment by alexch** [comment]
So, what version of Ruby are you using? `ruby --version` will tell you.

**Comment by RomanADavis** [comment]
ruby 1.9.3p551 (2014-11-13) [i386-mingw32]

**Comment by alexch** [comment]
Well there you go :-) . 1.9.3 is not between 2.0 and 2.5.

Rerun depends on Listen which depends on FFI for its filesystem scanning ability.

I see you're on Windows, so you can get Ruby 2.3 from http://railsinstaller.org/en . It should be mostly compatible with your tutorials, and if not, it's good that you learn the modern syntax of the language. Good luck and have fun with Ruby!
