### ISSUE TITLE
Publish Version 0.13.1

### ISSUE THREAD

**Issue by webnard** [alexch/rerun#126]

**Comment by baelter** [comment]
Yes, please, I want `--[no-]ignore-dotfiles`

**Comment by baelter** [comment]
@alexch

**Comment by baelter** [comment]
@alexch, pleeeeeease :)

**Comment by alexch** [comment]
DONE (Finally!)
![image](https://user-images.githubusercontent.com/8524/101686949-c523c480-3a37-11eb-9024-82b2943f59f3.png)

(Sorry, it's been a long year! :-) )
