### ISSUE TITLE
Q: is it possible to watch only one file? [SOLVED]

### ISSUE THREAD

**Issue by niam0r** [alexch/rerun#140]
Hi, I'm trying to get rerun to only restart the consumer whose own code has changed.
I have 2 consumers in `app/consumers`
So when using 
```
rerun --dir app/consumers bundle exec racecar ActivityLogConsumer
```
along with this in a different window:
```
rerun --dir app/consumers bundle exec racecar UserEventsNotificationConsumer 
```
when one of them changes, both are restarted.
Is there a way to specify one file only like this for example:
```
rerun --file app/consumers/activity_log_consumer.rb bundle exec racecar ActivityLogConsumer
```

Thanks

**Comment by niam0r** [comment]
Sorted, I realised I could use `--pattern` like this:
```
rerun --pattern {'activity_log_consumer.rb'} bundle exec racecar ActivityLogConsumer
```

**Comment by alexch** [comment]
Cool! Glad you got it to work.
-- 
Alex Chaffee - ***@***.***
http://alexchaffee.com
http://codelikethis.com
http://twitter.com/alexch
