### ISSUE TITLE
Error "undefined method `exists?' for FileTest:Module" when using the `FileTest.exists?` method

### ISSUE THREAD

**Issue by aristotelesbr** [alexch/rerun#142]
I'm encountering an error when using the `FileTest.exists?` method in a project that utilizes the open source library. The error occurs as follows:

Error: undefined method "exists?" for FileTest:Module (NoMethodError)
Location: `rerun-0.13.1/lib/rerun/watcher.rb:53`

```ruby
unless FileTest.exists?(d) && FileTest.readable?(d) && FileTest.directory?(d)
# ...
```

The error suggests that I should use the **`exist?`** method instead of `exists?`. I made this correction, and the error disappeared.

Steps to reproduce the error:

`rerun 'rackup'`

Environment:

Operating System: OsX BigSur 11.7.6
Ruby: 3.2.0

**Comment by ronan-mch** [comment]
This was fixed in #137. You should be able to resolve by updating to `>= 0.14.0`.
