### ISSUE TITLE
Support for a --exclude option

### ISSUE THREAD

**Issue by teddziuba** [alexch/rerun#24]
I'm using Rerun for for Python development with Heroku. (Long story short, the HTTP server I use in production doesn't support automatic-reloading, so I have rerun kicking foreman when there are code changes).

I use Emacs for development, with flymake mode to do on-the-fly syntax checking. It does this by copying the current buffer into a `[filename]_flymake.py` file and then running `pylint` on that file. This file creation kicks off rerun, so it's constantly bouncing my development HTTP server as I'm editing code.

I'd like to add my vote for a `--exclude` option that can take a glob pattern. I'd send you a pull myself, but I don't know enough Ruby.

Cheers

**Comment by PhilT** [comment]
--ignore is in master and 0.10. Is it stil WIP?

(It's not working for me)

**Comment by alexch** [comment]
--ignore should work. Can you show me your console output? It should say
"(ignoring xyz)" and such.​ Also do `rerun --version` to make sure you're
not using an old rev.

**Comment by PhilT** [comment]
Yeah, just got it working. Wasn't sure what folder was the root but now understand it's from whatever folders you're watching. When I got it wrong it was either not ignoring anything or ignoring odd files (ones I hadn't ignored).
