### ISSUE TITLE
Monitoring shared directories inside a vagrant VM doesn't work

### ISSUE THREAD

**Issue by fields** [alexch/rerun#39]
We're trying to use rerun to automatically restart a sinatra process inside a vagrant VM (ubuntu). The host is a Mac, and the source tree is in a shared directory. rerun starts, but doesn't detect changes on the files in the source tree.

Is there a way to get this to work? Is this a more appropriate issue for the listen gem?

**Comment by bawigga** [comment]
+1

**Comment by jorisroovers** [comment]
+1, this would be really useful

**Comment by ajduncan** [comment]
+1

**Comment by robkinyon** [comment]
Until this is fixed, could you modify the documentation to make it very clear that rerun doesn't work with Vagrant shared folders? Vagrant is rapidly becoming the de-facto development environment manager and this caused me several hours of debugging before I figured it out.

While shotgun isn't a great approach, a documentation fix should point to shotgun as the one that does work on Vagrant (for now).

**Comment by alexch** [comment]
Has anyone tried adding `force_polling: true` as suggested above? Also @robkinyon if you submit a README patch as a PR I will happily accept it.

**Comment by alexch** [comment]
I'm working on merging https://github.com/alexch/rerun/pull/80 now... if your git fu is strong, try installing this branch: https://github.com/alexch/rerun/tree/ajduncan-master and tell me if `--force-polling` works for you

**Comment by robkinyon** [comment]
--force-polling functions. I was able to "bundle exec rerun --force-polling
-- rackup -o 0.0.0.0 config.ru" and make changes and the changes would be
seen. So, it functions properly. Though, it would be nice if you defaulted
--force-polling if "-d /vagrant". (While that's not a guarantee of
Vagrant-ness, that is the default behavior.)

It also took up to 15 seconds for the changes to be seen. That's far more
disruptive than having to Ctrl-C/Up-Arrow or even "sudo service nginx
restart" (if I was using Passenger). Until that delay is under 2 seconds
(the time it takes for me to switch from editor to browser and hit Reload),
this isn't going to work. I'm not sure why the default of 1s for Listen's
polling adapter isn't working, but it was 15s.

This may be a problem with Virtualbox's shared folders, but you're going to
be the visible face of it. :(

On Thu, Nov 5, 2015 at 2:34 PM, Alex Chaffee <notifications@github.com>
wrote:

> I'm working on merging #80 <https://github.com/alexch/rerun/pull/80>
> now... if your git fu is strong, try installing this branch:
> https://github.com/alexch/rerun/tree/ajduncan-master and tell me if
> --force-polling works for you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexch/rerun/issues/39#issuecomment-154166717>.
>



-- 
Thanks,
Rob Kinyon
http://greenfishbluefish.com/

**Comment by alexch** [comment]
@robkinyon Thanks for digging in to this! Yeah, 15 seconds is bizarrely long. I wonder if it's a fundamental Virtualbox/Vagrant performance issue, or maybe it only shows up if you've got lots and lots of files (like in a git repo)...

Can you tell me more about your exact setup? Apparently you're running rerun inside a Guest OS shell using a Host OS filesystem (/vagrant) -- right? Can you run `find /vagrant -type f | wc` and `find /vagrant/.git -type f | wc` (or wherever your repo is stored)?

**Comment by alexch** [comment]
I finally installed Vagrant and reproduced this issue. It does seem to be a matter of the sheer number of watched files (or dirs). I suggest adding `-i .git -i tmp -i log` (ignore whatever directories you don't need to watch). (And yes, it's weird that `.git` isn't ignored by default; maybe that's a bug.)

I'm going to merge the `--force-polling` branch to master. I'm wary of your `--force-polling if "-d /vagrant"` suggestion but I think this will be solved by a `.rerun` config file so you can at least configure your own system to always poll.

**Comment by robkinyon** [comment]
Maybe those should also be default ignores. :-)

**Comment by athap** [comment]
Using master branch --force-polling option fixed the issue for me with docker

**Comment by alexch** [comment]
`--force-polling` is still the only solution for this inside rerun, but if you're still having trouble with Vagrant mounted dirs, Guard now supports network notifications, so the files can be watched on the host OS and then the behavior is triggered on the guest OS:

https://github.com/guard/guard/wiki/Command-line-options-for-Guard#running-guard-in-a-vm

Since rerun is supposed to be no-frills, I think we'll be punting on this one.

**Comment by alexch** [comment]
> > I suggest adding `-i .git -i tmp -i log`

> Maybe those should also be default ignores. :-)

They are now. But I can't remember if I added that list before or after you told me to :-)

```
    ignored_directories = %w[
      .git .svn .hg .rbx .bundle bundle vendor/bundle log tmp vendor/ruby
    ]
```
