### ISSUE TITLE
Allow monitoring of changes to files starting with a dot

### ISSUE THREAD

**Issue by robbles** [alexch/rerun#52]
I'm trying to get rerun to pick up changes to my `.env` file, used with Foreman. Restarting my server when code changes is working just fine, but ideally I'd like to have a workflow where I can change environment vars in `.env` and have the app auto-reload with new configuration.

I see that this is a deliberate built-in feature of the file globbing implementation. Turning this off could be a switch (e.g. `--no-ignore-dot`) or perhaps an implementation of the exclude option #24 could have leading dots, etc. as the default value, which could then be overridden.

I'm happy to give a shot at implementing this myself. Just wondering if it's already in progress or if you're opposed to the idea.

**Comment by atomaka** [comment]
Was progress made on this? Specific dotfiles are useful to watch for changes.

**Comment by alexch** [comment]
Implemented: https://github.com/alexch/rerun/commit/9a5ad390d536cb626a06ec9ca291499573580a6d
