### ISSUE TITLE
stty: standard input: unable to perform all requested operations

### ISSUE THREAD

**Issue by tuomasj** [alexch/rerun#62]
Any idea what outputs the following into the console when running rerun?
`"stty: standard input: unable to perform all requested operations"`

I'm running on OS X Maverick, ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin13.0] with rbenv and homebrew.

Everything works just fine, but the console gets filled with the warning.

Here is the log:

```
rerun --dir .,data,lib,views -- unicorn -E development

00:58:09 [rerun] App launched
stty: standard input: unable to perform all requested operations
I, [2014-06-14T00:58:10.137072 #28734]  INFO -- : listening on addr=0.0.0.0:8080 fd=9
I, [2014-06-14T00:58:10.137220 #28734]  INFO -- : worker=0 spawning...
I, [2014-06-14T00:58:10.138324 #28734]  INFO -- : master process ready
I, [2014-06-14T00:58:10.139132 #28736]  INFO -- : worker=0 spawned pid=28736
I, [2014-06-14T00:58:10.139568 #28736]  INFO -- : Refreshing Gem list
I, [2014-06-14T00:58:10.421355 #28736]  INFO -- : worker=0 ready
stty: standard input: unable to perform all requested operations
stty: standard input: unable to perform all requested operations
00:58:12 [rerun] Watching data, lib, views for **/*.{rb,js,coffee,css,scss,sass,erb,html,haml,ru,yml,slim,md} using Darwin adapter
stty: standard input: unable to perform all requested operations
stty: standard input: unable to perform all requested operations
stty: standard input: unable to perform all requested operations
stty: standard input: unable to perform all requested operations
^Crake aborted!
Interrupt:
```

**Comment by amikula** [comment]
I found this same problem on OSX Yosemite. For me, it turned out to be that I had GNU coreutils installed with homebrew, and rerun was finding that version of stty on my system. It's the "[stty -raw](https://github.com/alexch/rerun/blob/65664e55a9a87db2c19e15b5821b9d5ade7be16d/lib/rerun/runner.rb#L305)" call in runner.rb that's printing that message. I took that version of stty out of my path, and the problem went away.

Incidentally, calling stty -raw from the command line never causes that message. I'm not sure what the problem is exactly.

**Comment by alexch** [comment]
I'm not sure either, but I'm also guessing the message is coming from the
code inside rerun that temporarily switches the TTY mode so that it can
listen for keyboard commands.

https://github.com/alexch/rerun/blob/master/lib/rerun/runner.rb#L287-L306

TTY handling is mysterious.

**Comment by JikkuJose** [comment]
Any solution for this?

**Comment by alexch** [comment]
@JikkuJose did you try using the `-b` switch or making sure the PATH prefers the system `tty` command? Unfortunately if the TTY controls don't work, we can't look for on-the-fly key input.
