### ISSUE TITLE
Spawn in favor of fork: Supporting windows.

### ISSUE THREAD

**Issue by Billiam** [alexch/rerun#81]
For context: https://github.com/alexch/rerun/blob/master/lib/rerun/runner.rb#L141

Currently, the main rerun task runner uses Process.fork with an immediate call to `exec`. By itself, this is functionally equivalent to Process.spawn.

Replacing fork with spawn allows rerun to work correctly under windows (tested), particularly after the recent update to listen v3.

However, the forked version also wraps the exec call in a `begin...rescue` block, which the spawn spawn would not be able to replicate entirely. Wrapping the spawn call itself in a rescue does protect against immediate execute errors (ex: missing commands), but would require a little bit of refactoring in a few lines following, since pid may be nil for a failed spawn.

**Comment by alexch** [comment]
Neat! I didn't know `spawn` worked on Windows. But that's only half the trick... What about signals, telling the child to stop or HUP?

**Comment by Billiam** [comment]
The INT, TERM, and KILL signals are supported, but no luck for HUP. Is hup used in rerun, other than when passed in from the commandline?

**Comment by alexch** [comment]
finally got around to this in cf2ae08 -- I'll reboot into windows and test it soon

**Comment by alexch** [comment]
This is done; it's still glitchy but the next release (0.12.0) will have Windows support.
