### ISSUE TITLE
Double monitoring after installing ember

### ISSUE THREAD

**Issue by benoittgt** [alexch/rerun#85]
Hello

Initially posted here : 
https://github.com/rerun/rerun/issues/217#issuecomment-145638615

I'm working now on an ember project and it seems I have a conflict with guard:

I'm getting hundreds of errors like this one : 

```
        ** ERROR: directory is already being watched! **

        Directory: /Users/bti/code/myproject/front/tmp/srihash_assets-output_path-zeReLejw.tmp/front/templates/components/list-header

        is already begin watched through: /Users/bti/code/myproject/front/tmp/srihash_assets-output_path-zeReLejw.tmp/front/templates/components/list-header

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
```

My command is : 
```shell
rerun bin/rspec -b -p "**/*.{rb,js,jbuilder,coffee,css,scss,sass,erb,html,haml,ru,yml,slim,md}"
```

But it's the same with : 
```shell
rerun rspec spec/controllers/api/v1/applications_controller_spec.rb:98
```

It seems it's related to guard : https://github.com/guard/listen/wiki/Duplicate-directory-errors but I don't have the *listen* gem

**Comment by alexch** [comment]
I think you do have the listen gem... It's used by both Guard and Rerun to
provide the actual directory watching (listening) function.

Are you using Guard at the same time as Rerun?

Are any of those directories inside `srihash_assets-....tmp` symlinks?
Sounds like that would cause that problem.

In any case, I think a fix would be to explicitly specify the directories
you want to watch, and make sure "tmp" is not in the list. See the docs for
--dir

**Comment by benoittgt** [comment]
Thanks for your answer

```shell
 $ bundle list | grep listen
 $ gem list | grep listen
listen (2.10.1)
```

But `$ ps aux | grep guard` return nothing

I have many symlinks but all for files inside the tmp folder.

But.. as you mention `--dir` is the solution. My command is now 

```shell
rerun --dir app,spec,front/app bin/rspec -b -p "**/*.{rb,js,jbuilder,coffee,css,scss,sass,erb,html,haml,ru,yml,slim,md}"
```
I have to avoid `myproject/tmp` and `myproject/front/tmp`
