### ISSUE TITLE
Object#timeout is deprecated error under Ruby 2.3

### ISSUE THREAD

**Issue by mwpastore** [alexch/rerun#92]
Getting the following error under Ruby 2.3:

```
/home/mwp/.rbenv/versions/2.3.0-preview2/lib/ruby/gems/2.3.0/gems/rerun-0.11.0/lib/rerun/runner.rb:254:in `stop': Object#timeout is deprecated, use Timeout.timeout instead.
```

I'll be happy to be the guinea pig for any attempts at a patch.

**Comment by ibrahima** [comment]
Any plans to cut a release version with this PR? It'd be nice to make the warning go away in my console, without resorting to installing from Git. Thanks!
