### ISSUE TITLE
Polling option doesn't work in 0.11.0

### ISSUE THREAD

**Issue by nicolangr** [alexch/rerun#96]
when launch rerun with foreman and option --force-polling i have this error:

/usr/local/bundle/gems/rerun-0.11.0/lib/rerun/options.rb:109:in `parse': invalid option: --force-polling (OptionParser::InvalidOption)

Maybe this option is not enabled in this versions? from which version will be available?

**Comment by skrobul** [comment]
It's not released yet (see version history in the readme). If you want to use it, just install gem from github. Example entry in Gemfile:

```
gem 'rerun', github: 'alexch/rerun'
```

**Comment by epinault** [comment]
Any idea when this can be released? been quite a few month now. ran into the same issue and would love to be able  to use it without pointing to master

**Comment by nicolangr** [comment]
You have to point to repository in the  gem file lik in these example

**Comment by epinault** [comment]
I get that. but why not releasing the gem?

**Comment by krsyoung** [comment]
Would love to see a new version of this gem as well in order to get `--force-polling` without having to pull from GitHub!

**Comment by alexch** [comment]
I will release v0.12.0 ASAP! So so sorry for the wait.

**Comment by epinault** [comment]
thanks!
