### ISSUE TITLE
Feature request: "finish" control

### ISSUE THREAD

**Issue by pjscopeland** [alexch/rerun#98]
When running, the `x` or `q` keys terminate execution immediately.

When running with `--exit`, I might want to stop rerunning the command, but allow it to complete first. Being able to press (e.g.) `f` (for **f**inish) and have this happen would be a very useful option.

**Comment by alexch** [comment]
That's odd. Pressing `x` should send a TERM signal to the process to ask it to die gracefully before escalating a few seconds later to INT, then KILL. So if your app is exiting immediately, then maybe it's mishandling the TERM sig. I'm closing this issue for now but if you come back with more info -- what's your system? what app is this? -- then I'll reopen it.

**Comment by pjscopeland** [comment]
Well, no, if my app gets a `TERM` signal it probably expects to finish what it's doing and terminate as soon as possible; certainly, as you say, within a few seconds. I'm happy with how the 'e`x`it' command works.

The proposed "`f`inish" command would behave differently; it would not send a signal to the app, it would allow it to complete normally - which could be minutes away - and then terminate Rerun. Obviously the typical use case would be alongside the `--exit` option, but it could also be used to tell Rerun not to restart it if an app terminates unexpectedly as well.

**Comment by pjscopeland** [comment]
On the subject, a command to terminate the app but keep Rerun running might be helpful as well. Perhaps `s` for 'stop'?
