### ISSUE TITLE
Rerun is not restarting foreman/resque upon Redis disconnect

### ISSUE THREAD

**Issue by derwydd** [alexch/rerun#99]
I have used multiple options, none are working. "rerun foreman start"
Basically we have foreman to start the resque process. When redis goes down or is made unavailable, foreman workers crash. So we were looking into rerun to monitor foreman and restart it, if the workers fail because the redis connection stops. When I run "rerun foreman start" it starts up perfectly fine and works, as soon as I kill the redis connection to test, I get the below error and it will not restart automatically unless I type in "r".

Does anyone know of a solution? What am I doing wrong?

Thanks

user$ rerun  foreman start

12:47:35 [rerun] app launched
12:47:36 worker.1 | started with pid 31923
12:47:38 [rerun] Watching . for *_/_.{rb,js,coffee,css,scss,sass,erb,html,haml,ru,yml,slim,md,feature}
12:47:39 worker.1 | WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
12:48:30 worker.1 | rake aborted!
12:48:30 worker.1 | Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)

12:48:30 worker.1 | Errno::ECONNREFUSED: Connection refused - connect(2) for [::1]:6379
...
12:48:30 worker.1 | IO::EINPROGRESSWaitWritable: Operation now in progress - connect(2) would block
...
12:48:30 worker.1 | Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
...
12:48:30 worker.1 | Errno::ECONNREFUSED: Connection refused - connect(2) for [::1]:6379
...
12:48:30 worker.1 | IO::EINPROGRESSWaitWritable: Operation now in progress - connect(2) would block
...
12:48:30 worker.1 | /Users/user/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
12:48:30 worker.1 | Tasks: TOP => resque:work
12:48:30 worker.1 | (See full trace by running task with --trace)
12:48:30 worker.1 | exited with code 1
12:48:30 system   | sending SIGTERM to all processes

**Comment by mikwat** [comment]
I ran into a similar issue. It appears that when a process exits with code != 0 it isn't restarted, but I haven't verified this.

**Comment by alexch** [comment]
Did you try it with the `--exit` option?

> --exit (or -x) expect the program to exit. With this option, rerun checks the return value; without it, rerun checks that the launched process is still running.

Rerun is not intended as a process monitor, but more as a *filesystem change* monitor, which happens to (re)launch processes when files change. Look into dedicated tools like `god` or `monit` if you want a robust process monitor. 

<http://godrb.com/>

<https://mmonit.com/monit/>
